package cards

const (
	// Spades
	AceOfSpades    = Card(byte(SuitSpade<<SuitMaskOffset) | byte(RankAce))
	TwoOfSpades    = Card(byte(SuitSpade<<SuitMaskOffset) | byte(RankTwo))
	ThreeOfSpades  = Card(byte(SuitSpade<<SuitMaskOffset) | byte(RankThree))
	FourOfSpades   = Card(byte(SuitSpade<<SuitMaskOffset) | byte(RankFour))
	FiveOfSpades   = Card(byte(SuitSpade<<SuitMaskOffset) | byte(RankFive))
	SixOfSpades    = Card(byte(SuitSpade<<SuitMaskOffset) | byte(RankSix))
	SevenOfSpades  = Card(byte(SuitSpade<<SuitMaskOffset) | byte(RankSeven))
	EightOfSpades  = Card(byte(SuitSpade<<SuitMaskOffset) | byte(RankEight))
	NineOfSpades   = Card(byte(SuitSpade<<SuitMaskOffset) | byte(RankNine))
	TenOfSpades    = Card(byte(SuitSpade<<SuitMaskOffset) | byte(RankTen))
	JackOfSpades   = Card(byte(SuitSpade<<SuitMaskOffset) | byte(RankJack))
	KnightOfSpades = Card(byte(SuitSpade<<SuitMaskOffset) | byte(RankKnight))
	QueenOfSpades  = Card(byte(SuitSpade<<SuitMaskOffset) | byte(RankQueen))
	KingOfSpades   = Card(byte(SuitSpade<<SuitMaskOffset) | byte(RankKing))

	// Hearts
	AceOfHearts    = Card(byte(SuitHeart<<SuitMaskOffset) | byte(RankAce))
	TwoOfHearts    = Card(byte(SuitHeart<<SuitMaskOffset) | byte(RankTwo))
	ThreeOfHearts  = Card(byte(SuitHeart<<SuitMaskOffset) | byte(RankThree))
	FourOfHearts   = Card(byte(SuitHeart<<SuitMaskOffset) | byte(RankFour))
	FiveOfHearts   = Card(byte(SuitHeart<<SuitMaskOffset) | byte(RankFive))
	SixOfHearts    = Card(byte(SuitHeart<<SuitMaskOffset) | byte(RankSix))
	SevenOfHearts  = Card(byte(SuitHeart<<SuitMaskOffset) | byte(RankSeven))
	EightOfHearts  = Card(byte(SuitHeart<<SuitMaskOffset) | byte(RankEight))
	NineOfHearts   = Card(byte(SuitHeart<<SuitMaskOffset) | byte(RankNine))
	TenOfHearts    = Card(byte(SuitHeart<<SuitMaskOffset) | byte(RankTen))
	JackOfHearts   = Card(byte(SuitHeart<<SuitMaskOffset) | byte(RankJack))
	KnightOfHearts = Card(byte(SuitHeart<<SuitMaskOffset) | byte(RankKnight))
	QueenOfHearts  = Card(byte(SuitHeart<<SuitMaskOffset) | byte(RankQueen))
	KingOfHearts   = Card(byte(SuitHeart<<SuitMaskOffset) | byte(RankKing))

	// Diamonds
	AceOfDiamonds    = Card(byte(SuitDiamond<<SuitMaskOffset) | byte(RankAce))
	TwoOfDiamonds    = Card(byte(SuitDiamond<<SuitMaskOffset) | byte(RankTwo))
	ThreeOfDiamonds  = Card(byte(SuitDiamond<<SuitMaskOffset) | byte(RankThree))
	FourOfDiamonds   = Card(byte(SuitDiamond<<SuitMaskOffset) | byte(RankFour))
	FiveOfDiamonds   = Card(byte(SuitDiamond<<SuitMaskOffset) | byte(RankFive))
	SixOfDiamonds    = Card(byte(SuitDiamond<<SuitMaskOffset) | byte(RankSix))
	SevenOfDiamonds  = Card(byte(SuitDiamond<<SuitMaskOffset) | byte(RankSeven))
	EightOfDiamonds  = Card(byte(SuitDiamond<<SuitMaskOffset) | byte(RankEight))
	NineOfDiamonds   = Card(byte(SuitDiamond<<SuitMaskOffset) | byte(RankNine))
	TenOfDiamonds    = Card(byte(SuitDiamond<<SuitMaskOffset) | byte(RankTen))
	JackOfDiamonds   = Card(byte(SuitDiamond<<SuitMaskOffset) | byte(RankJack))
	KnightOfDiamonds = Card(byte(SuitDiamond<<SuitMaskOffset) | byte(RankKnight))
	QueenOfDiamonds  = Card(byte(SuitDiamond<<SuitMaskOffset) | byte(RankQueen))
	KingOfDiamonds   = Card(byte(SuitDiamond<<SuitMaskOffset) | byte(RankKing))

	// Clubs
	AceOfClubs    = Card(byte(SuitClub<<SuitMaskOffset) | byte(RankAce))
	TwoOfClubs    = Card(byte(SuitClub<<SuitMaskOffset) | byte(RankTwo))
	ThreeOfClubs  = Card(byte(SuitClub<<SuitMaskOffset) | byte(RankThree))
	FourOfClubs   = Card(byte(SuitClub<<SuitMaskOffset) | byte(RankFour))
	FiveOfClubs   = Card(byte(SuitClub<<SuitMaskOffset) | byte(RankFive))
	SixOfClubs    = Card(byte(SuitClub<<SuitMaskOffset) | byte(RankSix))
	SevenOfClubs  = Card(byte(SuitClub<<SuitMaskOffset) | byte(RankSeven))
	EightOfClubs  = Card(byte(SuitClub<<SuitMaskOffset) | byte(RankEight))
	NineOfClubs   = Card(byte(SuitClub<<SuitMaskOffset) | byte(RankNine))
	TenOfClubs    = Card(byte(SuitClub<<SuitMaskOffset) | byte(RankTen))
	JackOfClubs   = Card(byte(SuitClub<<SuitMaskOffset) | byte(RankJack))
	KnightOfClubs = Card(byte(SuitClub<<SuitMaskOffset) | byte(RankKnight))
	QueenOfClubs  = Card(byte(SuitClub<<SuitMaskOffset) | byte(RankQueen))
	KingOfClubs   = Card(byte(SuitClub<<SuitMaskOffset) | byte(RankKing))

	// Jokers
	RedJoker   = Card(byte(RankJoker) | byte(JokerSuitRed<<SuitMaskOffset))
	BlackJoker = Card(byte(RankJoker) | byte(JokerSuitBlack<<SuitMaskOffset))
	WhiteJoker = Card(byte(RankJoker) | byte(JokerSuitWhite<<SuitMaskOffset))

	// Major Arcana
	TheFool          = Card(ArcanaBit | Trump0TheFool)
	TheMagician      = Card(ArcanaBit | Trump1TheMagician)
	TheHighPriestess = Card(ArcanaBit | Trump2TheHighPriestess)
	TheEmpress       = Card(ArcanaBit | Trump3TheEmpress)
	TheEmperor       = Card(ArcanaBit | Trump4TheEmperor)
	TheHierophant    = Card(ArcanaBit | Trump5TheHierophant)
	TheLovers        = Card(ArcanaBit | Trump6TheLovers)
	TheChariot       = Card(ArcanaBit | Trump7TheChariot)
	Strength         = Card(ArcanaBit | Trump8Strength)
	TheHermit        = Card(ArcanaBit | Trump9TheHermit)
	WheelOfFortune   = Card(ArcanaBit | Trump10WheelOfFortune)
	Justice          = Card(ArcanaBit | Trump11Justice)
	TheHangedMan     = Card(ArcanaBit | Trump12TheHangedMan)
	Death            = Card(ArcanaBit | Trump13Death)
	Temperance       = Card(ArcanaBit | Trump14Temperance)
	TheDevil         = Card(ArcanaBit | Trump15TheDevil)
	TheTower         = Card(ArcanaBit | Trump16TheTower)
	TheStar          = Card(ArcanaBit | Trump17TheStar)
	TheMoon          = Card(ArcanaBit | Trump18TheMoon)
	TheSun           = Card(ArcanaBit | Trump19TheSun)
	Judgement        = Card(ArcanaBit | Trump20Judgement)
	TheWorld         = Card(ArcanaBit | Trump21TheWorld)
)
