package cards

func NewDeck32() Deck {
	return Deck([]Card{
		// Spades
		SevenOfSpades,
		EightOfSpades,
		NineOfSpades,
		TenOfSpades,
		JackOfSpades,
		QueenOfSpades,
		KingOfSpades,
		AceOfSpades,

		// Hearts
		SevenOfHearts,
		EightOfHearts,
		NineOfHearts,
		TenOfHearts,
		JackOfHearts,
		QueenOfHearts,
		KingOfHearts,
		AceOfHearts,

		// Diamonds
		SevenOfDiamonds,
		EightOfDiamonds,
		NineOfDiamonds,
		TenOfDiamonds,
		JackOfDiamonds,
		QueenOfDiamonds,
		KingOfDiamonds,
		AceOfDiamonds,

		// Clubs
		SevenOfClubs,
		EightOfClubs,
		NineOfClubs,
		TenOfClubs,
		JackOfClubs,
		QueenOfClubs,
		KingOfClubs,
		AceOfClubs,
	})
}

func NewDeck36() Deck {
	return Deck([]Card{
		// Spades
		SixOfSpades,
		SevenOfSpades,
		EightOfSpades,
		NineOfSpades,
		TenOfSpades,
		JackOfSpades,
		QueenOfSpades,
		KingOfSpades,
		AceOfSpades,

		// Hearts
		SixOfHearts,
		SevenOfHearts,
		EightOfHearts,
		NineOfHearts,
		TenOfHearts,
		JackOfHearts,
		QueenOfHearts,
		KingOfHearts,
		AceOfHearts,

		// Diamonds
		SixOfDiamonds,
		SevenOfDiamonds,
		EightOfDiamonds,
		NineOfDiamonds,
		TenOfDiamonds,
		JackOfDiamonds,
		QueenOfDiamonds,
		KingOfDiamonds,
		AceOfDiamonds,

		// Clubs
		SixOfClubs,
		SevenOfClubs,
		EightOfClubs,
		NineOfClubs,
		TenOfClubs,
		JackOfClubs,
		QueenOfClubs,
		KingOfClubs,
		AceOfClubs,
	})
}

func NewDeck52() Deck {
	return Deck([]Card{
		// Spades
		AceOfSpades,
		TwoOfSpades,
		ThreeOfSpades,
		FourOfSpades,
		FiveOfSpades,
		SixOfSpades,
		SevenOfSpades,
		EightOfSpades,
		NineOfSpades,
		TenOfSpades,
		JackOfSpades,
		QueenOfSpades,
		KingOfSpades,

		// Hearts
		AceOfHearts,
		TwoOfHearts,
		ThreeOfHearts,
		FourOfHearts,
		FiveOfHearts,
		SixOfHearts,
		SevenOfHearts,
		EightOfHearts,
		NineOfHearts,
		TenOfHearts,
		JackOfHearts,
		QueenOfHearts,
		KingOfHearts,

		// Diamonds
		AceOfDiamonds,
		TwoOfDiamonds,
		ThreeOfDiamonds,
		FourOfDiamonds,
		FiveOfDiamonds,
		SixOfDiamonds,
		SevenOfDiamonds,
		EightOfDiamonds,
		NineOfDiamonds,
		TenOfDiamonds,
		JackOfDiamonds,
		QueenOfDiamonds,
		KingOfDiamonds,

		// Clubs
		AceOfClubs,
		TwoOfClubs,
		ThreeOfClubs,
		FourOfClubs,
		FiveOfClubs,
		SixOfClubs,
		SevenOfClubs,
		EightOfClubs,
		NineOfClubs,
		TenOfClubs,
		JackOfClubs,
		QueenOfClubs,
		KingOfClubs,
	})
}

func NewDeck54() Deck {
	return Deck([]Card{
		// Spades
		AceOfSpades,
		TwoOfSpades,
		ThreeOfSpades,
		FourOfSpades,
		FiveOfSpades,
		SixOfSpades,
		SevenOfSpades,
		EightOfSpades,
		NineOfSpades,
		TenOfSpades,
		JackOfSpades,
		QueenOfSpades,
		KingOfSpades,

		// Hearts
		AceOfHearts,
		TwoOfHearts,
		ThreeOfHearts,
		FourOfHearts,
		FiveOfHearts,
		SixOfHearts,
		SevenOfHearts,
		EightOfHearts,
		NineOfHearts,
		TenOfHearts,
		JackOfHearts,
		QueenOfHearts,
		KingOfHearts,

		// Diamonds
		AceOfDiamonds,
		TwoOfDiamonds,
		ThreeOfDiamonds,
		FourOfDiamonds,
		FiveOfDiamonds,
		SixOfDiamonds,
		SevenOfDiamonds,
		EightOfDiamonds,
		NineOfDiamonds,
		TenOfDiamonds,
		JackOfDiamonds,
		QueenOfDiamonds,
		KingOfDiamonds,

		// Clubs
		AceOfClubs,
		TwoOfClubs,
		ThreeOfClubs,
		FourOfClubs,
		FiveOfClubs,
		SixOfClubs,
		SevenOfClubs,
		EightOfClubs,
		NineOfClubs,
		TenOfClubs,
		JackOfClubs,
		QueenOfClubs,
		KingOfClubs,

		// Jokers
		BlackJoker,
		WhiteJoker,
	})
}

func NewDeckTarot() Deck {
	return Deck([]Card{
		// Spades
		AceOfSpades,
		TwoOfSpades,
		ThreeOfSpades,
		FourOfSpades,
		FiveOfSpades,
		SixOfSpades,
		SevenOfSpades,
		EightOfSpades,
		NineOfSpades,
		TenOfSpades,
		JackOfSpades,
		KnightOfSpades,
		QueenOfSpades,
		KingOfSpades,

		// Hearts
		AceOfHearts,
		TwoOfHearts,
		ThreeOfHearts,
		FourOfHearts,
		FiveOfHearts,
		SixOfHearts,
		SevenOfHearts,
		EightOfHearts,
		NineOfHearts,
		TenOfHearts,
		JackOfHearts,
		KnightOfHearts,
		QueenOfHearts,
		KingOfHearts,

		// Diamonds
		AceOfDiamonds,
		TwoOfDiamonds,
		ThreeOfDiamonds,
		FourOfDiamonds,
		FiveOfDiamonds,
		SixOfDiamonds,
		SevenOfDiamonds,
		EightOfDiamonds,
		NineOfDiamonds,
		TenOfDiamonds,
		JackOfDiamonds,
		KnightOfDiamonds,
		QueenOfDiamonds,
		KingOfDiamonds,

		// Clubs
		AceOfClubs,
		TwoOfClubs,
		ThreeOfClubs,
		FourOfClubs,
		FiveOfClubs,
		SixOfClubs,
		SevenOfClubs,
		EightOfClubs,
		NineOfClubs,
		TenOfClubs,
		JackOfClubs,
		KnightOfClubs,
		QueenOfClubs,
		KingOfClubs,

		// Major Arcana
		TheFool,
		TheMagician,
		TheHighPriestess,
		TheEmpress,
		TheEmperor,
		TheHierophant,
		TheLovers,
		TheChariot,
		Strength,
		TheHermit,
		WheelOfFortune,
		Justice,
		TheHangedMan,
		Death,
		Temperance,
		TheDevil,
		TheTower,
		TheStar,
		TheMoon,
		TheSun,
		Judgement,
		TheWorld,
	})
}

func NewDeckFull() Deck {
	return Deck([]Card{
		// Spades
		AceOfSpades,
		TwoOfSpades,
		ThreeOfSpades,
		FourOfSpades,
		FiveOfSpades,
		SixOfSpades,
		SevenOfSpades,
		EightOfSpades,
		NineOfSpades,
		TenOfSpades,
		JackOfSpades,
		KnightOfSpades,
		QueenOfSpades,
		KingOfSpades,

		// Hearts
		AceOfHearts,
		TwoOfHearts,
		ThreeOfHearts,
		FourOfHearts,
		FiveOfHearts,
		SixOfHearts,
		SevenOfHearts,
		EightOfHearts,
		NineOfHearts,
		TenOfHearts,
		JackOfHearts,
		KnightOfHearts,
		QueenOfHearts,
		KingOfHearts,

		// Diamonds
		AceOfDiamonds,
		TwoOfDiamonds,
		ThreeOfDiamonds,
		FourOfDiamonds,
		FiveOfDiamonds,
		SixOfDiamonds,
		SevenOfDiamonds,
		EightOfDiamonds,
		NineOfDiamonds,
		TenOfDiamonds,
		JackOfDiamonds,
		KnightOfDiamonds,
		QueenOfDiamonds,
		KingOfDiamonds,

		// Clubs
		AceOfClubs,
		TwoOfClubs,
		ThreeOfClubs,
		FourOfClubs,
		FiveOfClubs,
		SixOfClubs,
		SevenOfClubs,
		EightOfClubs,
		NineOfClubs,
		TenOfClubs,
		JackOfClubs,
		KnightOfClubs,
		QueenOfClubs,
		KingOfClubs,

		// Major Arcana
		TheFool,
		TheMagician,
		TheHighPriestess,
		TheEmpress,
		TheEmperor,
		TheHierophant,
		TheLovers,
		TheChariot,
		Strength,
		TheHermit,
		WheelOfFortune,
		Justice,
		TheHangedMan,
		Death,
		Temperance,
		TheDevil,
		TheTower,
		TheStar,
		TheMoon,
		TheSun,
		Judgement,
		TheWorld,

		// Jokers
		BlackJoker,
		WhiteJoker,
		RedJoker,
	})
}
